src/rccl.cpp
src/rcclAllReduceKernels.h
src/rcclAllReduceRuntime.h
src/rcclBroadCastKernels.h
src/rcclBroadCastRuntime.h
src/rcclKernelHelper.h
src/rcclTracker.h
tests/validation/rcclAllReduce.cpp
tests/validation/rcclBcast.cpp
tests/validation/runDeepBench.sh

Finished rcclAllReduce and rcclBcast primitives.
All validation tests passed.

Finished rcclAllReduce and rcclBcast

---

src/Makefile
tests/conformance/Makefile
tests/conformance/rcclCommInitAll.cpp
tests/coverage/Makefile
tests/performance/Makefile
tests/performance/rcclAllReduce.cpp
tests/performance/rcclReduceScatter.cpp
tests/stress/Makefile
tests/validation/Makefile
tests/validation/validate.h

Fixed for centos and cleaned up test makefiles

Centos fix

---

.travis.yml

Adding rccl to travis ci - just as build test

added rocm install script for travis ci

---

CMakeLists.txt
inc/rccl/rccl.h
src/CMakeLists.txt
src/Makefile
src/rcclAllGather.cpp
src/rcclScalarAllGatherKernels.h
src/rcclScalarAllGatherRuntime.h

add allgather support

---

tests/validation/validate.h

This also fixes issue https://github.com/ROCmSoftwarePlatform/rccl/issues/34

Specialize validation for __fp16

---

CMakeLists.txt
inc/rccl/rccl-version.h.in
src/Makefile
src/rccl.cpp

generate rccl-version.h and install it

add rccl-version.h

---

src/Makefile

Fix Makefile by parsing CMakeLists.txt manually so correct version number is used.

add version string parsing to Makefile

---

CMakeLists.txt
inc/rccl.h
src/Makefile
src/rcclReduceScatter.cpp
src/rcclScalarReduceScatterKernels.h
src/rcclScalarReduceScatterRuntime.h

```bash
$ build/reduce_scatter_perf -b 32 -e 128M -f 2 -g 4
nThread 1 nGpus 4 minBytes 32 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 1 
32             2   float     sum    0.079   0.00   0.00    1e-07    0.082   0.00   0.00    2e-07
64             4   float     sum    0.152   0.00   0.00    2e-07    0.152   0.00   0.00    2e-07
128             8   float     sum    0.151   0.00   0.00    2e-07    0.152   0.00   0.00    2e-07
256            16   float     sum    0.153   0.00   0.00    2e-07    0.152   0.00   0.00    2e-07
512            32   float     sum    0.168   0.00   0.00    5e-07    0.150   0.00   0.00    2e-07
1024            64   float     sum    0.148   0.01   0.01    5e-07    0.150   0.01   0.01    2e-07
2048           128   float     sum    0.150 …
```

add reduce scatter support

---

inc/rccl.h
src/rccl.cpp

SWDEV-171181
How to test:
rccl/tests/validation$ RCCL_TRACE_RT=1 bin/commBcast 2
<<rccl-api: rcclGetUniqueId uniqueId:139723509142336
<<rccl-api: rcclCommInitRank RCCL version 0.7.1 comm:0x7f13ea21d7c0 ndev:2, commId:139723509142336 rank:0
<<rccl-api: rcclCommInitRank RCCL version 0.7.1 comm:0x7f13ea21d7c8 ndev:2, commId:139723509142336 rank:1
<<rccl-api: rcclCommDestroy comm:0x7f13ea21d9a0
<<rccl-api: rcclCommInitRank RCCL version 0.7.1 comm:0x7f13ea21d7c0 ndev:2, commId:139723509142336 rank:0
<<rccl-api:rcclBcast rccl-device:0 buff:0x2404800000 count:2097152 datatype:rcclFloat root:0 comm:0x7f13ea21d9a0 stream:0x7f13ea21d8d0
<<rccl-api:rcclBcast rccl-device:1 buff:0x2405200000 count:2097152 datatype:rcclFloat root:0 comm:0x7f13ea21dc80 stream:0x7f13ea21f010
Validating on GPU: 0 …

change rcclUniqueId to a string representation of the pointer value

---

CMakeLists.txt
inc/rccl.h
src/rccl.cpp

requested by Jithun for PyTorch porting

use const devlist and increment library version to 0.7.2

---

src/rcclBarrierKernels.h
src/rcclSetKernels.h
src/rcclTracker.cpp
src/rcclTracker.h

- Anonymous namespace around common kernels.
- extern declare trace symbols API_COLOR, API_COLOR_END.

Fix duplicate symbols.

---

test/CMakeLists.txt
test/CorrectnessTest.hpp
test/test_CombinedCalls.cpp
test/test_CombinedCalls.hpp

Simple test where different collectives are queued on a per-thread basis.

Test combined calls

---

Jenkinsfile
install.sh

Working Jenkins unit tests and updated install.sh file. 
This should be merge squashed. 
After this all Jenkins work will be done in a personal fork.

Jenkinsfile

---

README.md
docs/source/conf.py

Readme update

---

tools/rccl-prim-test/rccl_prim_test.cpp

Allow easier data collection during debug

rccl-prim-test: print GPU info and set iterations

---

tools/rccl-prim-test/rccl_prim_test.cpp

Get kernel level throughput through RTC counters

Calculate and print kernel throughput

---

CMakeLists.txt

I am doing this temporarily. I am waiting for legal's reponse on mailing lists for package maintainers.

Changing maintainer to no-reply to fix deb generation

---

README.md
install.sh

Also cleaned up unused command-line arguments and weird tabs in the install script too.

Fixing install script to actually install library when requested

---

tools/rccl-prim-test/rccl_prim_test.cpp

To get more accurate reflection of primitives performance

Match primitives unroll counts with latest RCCL

---

src/init.cu

Removed hack and debug printf. Will not help unless HIP PCI device ID fix is merged. But merging this patch will do no harm either.

Allocate transport memory based on numa node

---

src/include/core.h
src/init.cu
src/misc/enqueue.cu

Depends on HIP version with this pull request:
https://github.com/ROCm-Developer-Tools/HIP/pull/1232

Use hipExtLaunchMultiKernelMultiDevice API

---

src/include/core.h
src/ring.cu
src/transport/p2p.cu

Remove dependency to HSA_FORCE_FINE_GRAIN_PCIE flag for XGMI link

---

tools/TransferBench/Makefile
tools/TransferBench/TransferBench.cpp
tools/TransferBench/TransferBench.hpp
tools/TransferBench/copy_kernel.h
tools/TransferBench/example.cfg

standalone TransferBench tool
Used to measure simultaneous peer-to-peer performance on a single node, in user-specified configurations.

Adding TransferBench tool

---

src/collectives/device/primitives.h
src/include/enqueue.h
src/init.cc

Also move back abort check to after SPINS_BEFORE_CHECK_ABORT

Tune LL threshold for VEGA

---

src/collectives/device/common.h
src/collectives/device/common_kernel.h
src/collectives/device/primitives.h
src/collectives/device/reduce_kernel.h
src/include/devcomm.h
src/include/rings.h
src/init.cc
src/misc/rings.cc
src/transport/net_ib.cc
src/transport/p2p.cc

- Add necessary function attribute for HIP programming model.
- Explicitly include hsa headers.

Fix build with hip-clang.

---

src/collectives/device/all_gather.cu
src/collectives/device/all_reduce.cu
src/collectives/device/broadcast.cu
src/collectives/device/common_kernel.h
src/collectives/device/reduce.cu
src/collectives/device/reduce_scatter.cu

Also remove all unused UNROLL defines

Tune AUTOUNROLL for better performance

---

pkg/redhat/nccl.spec.in
src/include/socket.h
src/include/utils.h
src/init.cc
src/misc/utils.cc

Upstream sync

---

src/transport/p2p.cc

To avoid remote P2P read access when checking remote GPU's opCount

Allocate opCount in pinned host memory for P2P transport

---

src/collectives/device/common.h

Only copy and sum kernels should be generated. We are generating more kernels than needed.

Only generate kernels for sum and copy

---

src/collectives/collectives.h
src/collectives/device/common.h
src/enqueue.cc

Need to tune and specify NCCL_TREE_THRESHOLD to allow usage

Enable tree kernels in build

---

tools/TransferBench/TransferBench.cpp

Minor formatting fixes as well

Adding interactive mode for profiling purposes

---

tools/rccl-prim-test/rccl_prim_test.cpp

Allow user specified ring topology from command line and duplicated
to requested number of workgroups:
./rccl_prim_test -w 12 -p copy -r "0 1 2 3|3 2 1 0|0 2 1 3|3 1 2 0|0 2 3 1|1 3 2 0"

rccl_prim_test: Generalize ring topology and duplications

---

CMakeLists.txt
src/collectives/collectives.h
src/collectives/device/common.h
src/collectives/device/common_kernel.h
src/collectives/device/reduce_kernel.h
src/enqueue.cc
src/include/core.h
src/include/devcomm.h
src/include/rccl_bfloat16.h
src/nccl.h.in
test/CorrectnessTest.hpp
test/test_AllGather.cpp
test/test_AllReduce.cpp
test/test_AllReduce.hpp
test/test_Broadcast.cpp
test/test_CombinedCalls.cpp
test/test_GroupCalls.cpp
test/test_Reduce.cpp
test/test_Reduce.hpp
test/test_ReduceScatter.cpp
test/test_ReduceScatter.hpp

RCCL API version is updated to 2.5.0

Add bfloat16 support in RCCL

---

src/collectives/device/primitives.h

Direct accessing remote GPU's input/output buffers from same process is not supported. So disable it from compilation to reduce scratch memory size.

Disable direct buffers to reduce scratch memory size

---

CMakeLists.txt

We need CI on RHEL, caught mistake in syntax manually.

Package fix

---

tools/TransferBench/TransferBench.cpp
tools/TransferBench/TransferBench.hpp

Fixing missing header include for ROCM 3.0 changes

Adding new sleep after sync capability for data fabric profiling

---

CMakeLists.txt
install.sh

1. Set soversion to match release version

Changes for multiple ROCm installation

---

src/graph/connect.cc
src/graph/search.cc

Also change level of ring graph print to help debugging

Fix incorrect CR8 detection

---

makefiles/common.mk
makefiles/version.mk
pkg/debian/Makefile
src/collectives/device/primitives.h
src/graph/paths.cc
src/graph/tuning.cc
src/init.cc

Bring in memory leak and 4GB data size fixes

Sync up with NCCL 2.5.7

---

src/graph/search.cc

This reverts previous workaround of deducting only half of width
from paths.

Use fraction of system maxWidth as steps for searching

---

src/graph/connect.cc

Fix insufficent number of rings on single node after pull #179

Remove condition for ring duplication

---

tools/rccl-prim-test/copy_kernel.h
tools/rccl-prim-test/rccl_prim_test.cpp

For gfx908, support simple detection of ring topology.
Call ReduceOrCopyMulti directly from kernel.
Also simplify code by removing kernel start synchronization option
which has no effect on throughput measurements.

rccl-prim-test: add all-to-all benchmark

---

src/include/rccl_bfloat16.h

Update rccl_bfloat16.h to match rocBLAS

---

src/collectives/device/all_reduce.h

This reverts commit eec319038e88920693484e997880add000e0c7cd.

Revert "Tuning the inline and unroll to reduce the scratch usage"

---

README.md
docs/source/api.rst
install.sh
src/nccl.h.in

Adding the new API calls to the documentation.

Documentation updates for NCCL 2.7.0

---

CMakeLists.txt
src/include/devcomm.h
src/transport/net.cc

Revert use posix_memalign for network buffer allocation on host memory

---

src/graph/connect.cc
src/graph/search.cc

1. Use bi-directional rings
2. GPU search is sorted by PCI device ID to get consistent results

Improve 4P2H topology on Rome

---

tools/rccl-prim-test/rccl_prim_test.cpp

Adding doublelocalcopy operation and freeing buffer memory at end.
DoubleLocalCopy Patch Added

Adding doublelocalcopy operation to prim tests

---

tools/scripts/rccl_bw_test.py

Add rccl bw test script. This script enabled mnode multiple iteration rccl bw test (e.g. all_reduce_perf) witrandom HIP_VISIBLE_DEVICES assignment

Rccl test script

---

tools/TransferBench/Makefile
tools/TransferBench/TransferBench.cpp
tools/TransferBench/TransferBench.hpp
tools/TransferBench/example.cfg

Various TransferBench updates / changes:
- Expanding Link definition to (execution GPU, srcMemory, dstMemory), allowing for remote read / remote write / pinned CPU memory support.
- Modifications to how configFile is defined
- Changes to how output is displayed (now listed per link, instead of amalgamated per GPU)
- Cleanup of environment variable listing / output

New TransferBench features

---

.jenkins/common.groovy
.jenkins/precheckin.groovy

Ubuntu testing will be added again later.

Adding sles15, centos7 and centos8 testing

---

tools/TransferBench/TransferBench.cpp

Displays PCIe Bus ID for each GPU when TransferBench is run without any arguments

[TransferBench] Displaying PCIe Bus ID

---

src/graph/xml.cc

Use device's link width and speed if port doesn't report

---

tools/TransferBench/EnvVars.hpp
tools/TransferBench/Makefile
tools/TransferBench/TransferBench.cpp
tools/TransferBench/TransferBench.hpp
tools/TransferBench/example.cfg

- Adding new ability to execute copies via CPU
- Breaking changes to how config files are formatted (SRC->EXE->DST)
- Refactoring how environment variables are handled (setting to 0 works as expected)
- Adding fine-grained memory as a specifiable memory type ('F')
- Removing some un-used features
- Changing threading
- Adding multi-threaded CPU-based memcopies (NUM_CPU_PER_LINK)
- Fixes to CSV output
- More clarity on link type

[TransferBench] Adding ability to perform CPU-executed copies, various upgrades

---

src/init.cc

Fix test stuck on Nav21 which doesn't support  cooperative multi device launch

Add detection of cooperative multi device launch attribute

---

CMakeLists.txt

Remove link to NUMA lib as it is no longer needed

---

src/collectives/device/common_kernel.h
src/graph/search.cc
tools/rccl-prim-test/copy_kernel.h
tools/rccl-prim-test/rccl_prim_test.cpp

Limit max channels for ring graph on single node Rome

---

CMakeLists.txt

http://ontrack-internal.amd.com/browse/SWDEV-283157

Add libdl linking option

---

src/enqueue.cc
src/include/devcomm.h

Use fixed segment size for sendrecv

---

src/clique/CliqueManager.cc

Retuning based on OAM performance

Tweak clique channel usage for gfx908

---

src/graph/rome_models.cc

Add support for another Rome model

---

CHANGELOG.md
install.sh

Do not merge until PM approval given.

Cherry-picking install script fix for ROCm 4.3.

---

src/graph/rome_models.cc

SWDEV-289827, approved for merging to 4.3

Add support for another Rome model (#385)

---

tools/TransferBench/EnvVars.hpp

Changing to using big-endian to specify fill pattern for TransferBench

[TransferBench] Switching from little-endian fill pattern to big-endian

---

.jenkins/staticanalysis.groovy
src/nccl.h.in

(cherry picked from commit 1c982d819d9c7fe0310b80f9a25808e54c71137e)

Skipping unnecessary functions in Doxygen by marking as internal (#353)

---

src/graph/rome_models.cc
test/CorrectnessTest.hpp
test/test_AllGather.cpp
test/test_AllReduce.cpp
test/test_AllReduceAbort.cpp
test/test_AllReduceGroup.cpp
test/test_Broadcast.cpp
test/test_BroadcastAbort.cpp
test/test_CombinedCalls.cpp
test/test_GroupCalls.cpp
test/test_Reduce.cpp
test/test_ReduceScatter.cpp

Add NPS=4 model

---

tools/TransferBench/TransferBench.cpp

- Lines starting with ## in config file will now be echoed to output

[TransferBench] Adding comment echoing to help distinguish tests

---

CMakeLists.txt
src/collectives/device/common.h

Support all protocols and algorithms, including clique with floast32 and sum.
[100%] Built target rccl
real	4m52.958s
user	51m6.430s
sys	5m39.457s

Support different protocols and algorithms in all reduce only build

---

tools/TransferBench/TransferBench.cpp
tools/TransferBench/TransferBench.hpp

- Adding ability to filter between local read / remote read for peer to peer benchmarks
- Adding ability to skip CPU devices for peer to peer benchmarks

[TransferBench] Adding more preset benchmarks

---

tools/TransferBench/TransferBench.cpp

This deals with cases where the configured NUMA nodes are not 0,1,...# configured numa nodes - 1.

[TransferBench] Fix for cases with subsets of configured numa nodes

---

test/AllReduce_GroupCall.cpp
test/AllReduce_PreMultScalar.cpp
test/SendRecv_SinglePairs.cpp

- Adding check against process mask for custom unit tests
- Removing execute mode status from SendRecv_SinglePairs.cpp

[UnitTests] Check process mask for custom tests

---

src/nccl.h.in

Changed the Doxygen command for ncclRecv and pncclRecv, to be consistent with other APIs.

Doxygen fix for ncclRecv

---

CHANGELOG.md
src/bootstrap.cc
src/graph/connect.cc
src/graph/paths.cc
src/graph/rome_models.cc
src/graph/search.cc
src/graph/topo.cc
src/graph/topo.h
src/graph/xml.h
src/group.cc
src/include/comm.h
src/include/group.h
src/include/transport.h
src/init.cc
src/nccl.h.in
src/transport/p2p.cc
test/SendRecv_SinglePairs.cpp
test/common/EnvVars.cpp
test/common/EnvVars.hpp
test/common/TestBed.cpp
test/common/TestBed.hpp
test/common/TestBedChild.cpp
tools/MultiRank/Makefile
tools/MultiRank/README.mpi
tools/MultiRank/rccl-allreduce-mpi-multirank.cc
tools/MultiRank/rccl-allreduce-multirank.cc
tools/MultiRank/rccl-reducescatter-mpi-multirank.cc
tools/MultiRank/rccl-reducescatter-multirank.cc
tools/topo_expl/include/model.h

bring support for multiple ranks per GPU to the public rccl repository.

Multi rank devel

---

CMakeLists.txt

Proposed changes for GNUInstall dir enhancements

[CMake] GNU Install Dir Enhancements

---

src/collectives/device/common_kernel.h
src/graph/paths.cc
src/graph/search.cc
src/graph/topo.h

This reverts commit b250c01cbe06af0935461fecfa052c9a7d28c9ef.

Revert "Use nontemporal in slow path and add XGMI sys type (#575)"

---

test/AllReduce_Clique.cpp

- Disabling Unit test for clique-based allreduce

Disable clique AllReduce UnitTest

---

src/graph/paths.cc
src/graph/search.cc
src/graph/topo.h

Re-submit part of https://github.com/ROCmSoftwarePlatform/rccl/pull/575

Add XGMI sys type and clean up detection code

---

test/AllReduce_OutOfPlace.cpp
test/AllToAllv_OutOfPlace.cpp
test/Gather_InPlace.cpp
test/ReduceScatter_InPlace.cpp
test/ReduceScatter_OutOfPlace.cpp
test/common/EnvVars.cpp
test/common/PtrUnion.cpp
test/common/PtrUnion.hpp

lets see what CI  thinks about this :-)
Will ask for reviews once we pass CI, since I am not 100% convinced that this is completely correct.

introduce support for ncclFloat16/half in UT

---

CHANGELOG.md
src/enqueue.cc
src/include/alloc.h
src/include/param.h
src/include/rccl_vars.h
src/init.cc

Enabling opt-in of hipGraph support within RCCL

Adding opt-in hipGraph support for RCCL via RCCL_ENABLE_HIPGRAPH

---

tools/GraphBench/GraphBench.cpp
tools/GraphBench/Makefile

Simple standalone tool to compare hipGraph vs non-hipGraph allReduce

GraphBench

---

src/channel.cc
src/clique/CliqueManager.cc
src/include/alloc.h
src/include/comm.h
src/init.cc
src/transport.cc
src/transport/coll_net.cc
src/transport/net.cc
src/transport/p2p.cc
tools/ib-test/ib_test.cpp

- Adding new optional stream to ncclCudaCalloc
- Adding a sideStream to ncclComm with same lifetime as communicator
- Using sideStream in calls to ncclCudaCalloc where comm is available
- Changing a test cudaCalloc to a cudaMalloc

Updating stream caching

---

src/collectives/device/all_reduce.h
src/enqueue.cc
src/graph/connect.cc
src/include/devcomm.h
src/include/graph.h
src/init.cc

In addition, introduce the ability to have 2 trees at the same time. Only for allreduce at the moment.

add binary tree

---

src/collectives/device/prims_ll.h
src/collectives/device/prims_simple.h
tools/rccl-prim-test/copy_kernel.h

Remove #pragma unroll 1 for places known not unrollable.
Instill #pragma unroll on places known to be unrollable.

Tweak unroll factors.

---

src/collectives/device/primitives.h
src/collectives/device/prims_ll.h
src/collectives/device/prims_ll128.h
src/collectives/device/prims_simple.h

Empirical testing shows slight improvements in larger message sizes.

Reduce s_sleep cycles

---

src/enqueue.cc
src/graph/connect.cc
src/include/graph.h
src/init.cc

introduce a hw topology aware bintree

---

test/common/TestBedChild.cpp

- Switching to relaxed stream capture for unit testing

Switching to relaxed capture for unit tests

---

CMakeLists.txt

Adding -pthread flag for linking issues into CMakeLists.txt

Adding -pthread flag into CMakeLists.txt

---

test/CMakeLists.txt
test/Multistream.cpp
test/common/CollectiveArgs.cpp
test/common/CollectiveArgs.hpp
test/common/TestBed.cpp
test/common/TestBed.hpp
test/common/TestBedChild.cpp
test/common/TestBedChild.hpp

- Updating unit test framework to support initializing comms to allow for multiple streams, and specifying different streams per collective.
- Adding a basic multi-stream test

Multi stream unit test

---

test/common/EnvVars.cpp
test/common/EnvVars.hpp
test/common/TestBed.cpp
test/common/TestBed.hpp
test/common/TestBedChild.cpp

- Adding ability to run unit tests in interactive mode via environment variable (set UT_INTERACTIVE=1)

Adding interactive mode for unit tests (UT_INTERACTIVE)

---

tools/scripts/npkit_trace_generator.py

Trace generator stats should provide average time per gpu

added time results on npkit generator

---

src/graph/paths.cc
tools/topo_expl/Makefile
tools/topo_expl/utils.cpp

Also fix topol_expl build issue

Add NCCL_NCHANNELS_PER_PEER override

---

.jenkins/common.groovy
.jenkins/extended.groovy
.jenkins/precheckin.groovy
.jenkins/staticanalysis.groovy
.jenkins/staticlibrary.groovy
LICENSE.txt
NOTICES.txt
tools/scripts/rccl_bw_test.py

- Adding missing license information to .jenkins files
- Updating NOTICES.txt to latest NCCL version, adding NPKit notice
- Minor whitespace fixes

Updating NOTICES.txt and LICENSE.txt

---

CMakeLists.txt
src/misc/msccl/msccl_lifecycle.cc

Summary of proposed changes:
- Changes for ASAN Packaging [SWDEV-398093]
- Will enable only required files for ASAN Packaging. (library and License file)
- Enable support for AlgoDir to move to generic location
-

ASAN build excluding additional files, Algodir support for share folder

---

CMakeLists.txt
src/collectives/device/common.h
src/graph/paths.cc
src/graph/rome_models.cc
src/graph/search.cc
src/graph/topo.cc
src/graph/topo.h
src/include/alloc.h
src/init.cc
src/misc/msccl/msccl_lifecycle.cc
src/misc/npkit.cc
src/transport/net.cc
src/transport/p2p.cc
tools/scripts/topo_val.sh
tools/topo_expl/topo_expl.cpp

(cherry picked from commit 94da229a7788d74685d1591a4e75a8341de64f41)

Enable gfx94x (#808)

---

CMakeLists.txt
src/collectives/device/common.h
src/graph/tuning.cc

This reverts commit 420f8af6a0f167a4b062b45fd3e5ef607c96b965.
Also increase number of parallel jobs for linking

Revert "Enable Ll128 on gfx90a (#823)"

---

CMakeLists.txt
src/graph/tuning.cc

Also increase number of parallel jobs for linking

Protocol selection needs to follow ENABLE_LL128

---

src/collectives/device/prims_simple.h
src/graph/tuning.cc

(cherry picked from commit 8e58b6587317ea9e851760d739d2c078777ca065)

gfx11xx: disable LL protocol to workaround mtype issue (#840)

---

test/SendRecvTests.cpp

Tested it with NCCL to make sure we have the same results.

0-byte test for send/recv

---

CMakeLists.txt
install.sh

as $title, now command "install.sh --static" runs, however the static lib build failed, probably need RCCL team to take further look.

Update install.sh to take "--static" option

---

tools/EmptyKernelTest/EmptyKernelTest.cpp
tools/EmptyKernelTest/Makefile

This test is measuring kernel launch latency in both hip and cuda platforms.

adding cuda support for EmptyKernelTest

---

CMakeLists.txt

Reverts ROCmSoftwarePlatform/rccl#954

Revert "Remove hip::device"
