src/rcclBarrierKernels.h
src/rcclTracker.cpp
src/rcclTracker.h

HIP atomics do not provide load and store operations. They are instead emulated using atomicAdd and atomicExch, respectively.

Fix #54. Replace std::atomic with HIP atomic.

---

test/CorrectnessTest.hpp
test/test_AllGather.cpp
test/test_AllReduce.cpp
test/test_Broadcast.cpp
test/test_GroupCalls.cpp
test/test_Reduce.cpp
test/test_ReduceScatter.cpp

Added sample alignment test for AllGather
Datasets no longer free memory on destruction so Release() must be used

Adding support for alignment tests via sub-datasets

---

test/CorrectnessTest.hpp

GTEST_SKIP() does not currently exist in the Google test 1.8.1.
For now, avoid segmentation fault from unnecessary frees/teardown by resetting numDevices to 0 / numAvailableDevices to -1.

Adding fix for unsufficient devices / better logging for skipped tests

---

README.md

Fixing readme as per Dan's request.
Also updating based on new install.sh. I am following the rest of rocm math libraries and requiring -i option to install to /opt/rocm/

Updating readme for 2.5 release

---

CMakeLists.txt
src/collectives/device/common.h
src/transport/p2p.cu

This is a partial fix.
There are some other issues related to indirect function call, but we need to fix these issues first to see the other issues.

Fix build failure for hip-clang

---

src/transport/p2p.cu

Improve throughput for about 20%. Also remove P2P over PCIe which was
left enabled at initial release.
Signed-off-by: Wenkai Du <wenkai.du@amd.com>

Increase number of rings with XGMI connection

---

src/collectives/device/common.h
src/collectives/device/functions.cu

This is necessary to constant propagate the function pointers
to eliminate the indirect function call.

Make ncclFuncs static

---

src/init.cu

We do not need an internal stream.  This improves performance of framework integrations.

do not use internal stream

---

src/collectives/device/primitives.h

Fine tuning UNROLL for different primitives. Improved busbw > 10%

Use different unroll numbers for copy and reduce

---

CMakeLists.txt

- Fixing Centos 7 Packaging
-  standardizing version numbers for release to use rocm versioning
- removing maintainer email based on legal's input

Fixing Centos 7 Packaging and package versioning/maintainer

---

src/include/transport.h
src/include/utils.h
src/init.cu
src/misc/utils.cu
src/transport/net.cu
src/transport/p2p.cu
src/transport/shm.cu

Current SHM object name would only use pidHash and ranks as
identification, which would collide each other when program runs with
multiple communicators. Here we added commId info into pidHash, it makes
'pidHash'es of different communicators keeping in same process will be
distincted with each other.
Ported from original commit: https://github.com/lowintelligence/nccl/commits/shm

Fix share memory collision in multi-communicator case.

---

src/collectives/device/all_gather.h
src/collectives/device/all_reduce.h
src/collectives/device/broadcast.h
src/collectives/device/reduce.h
src/collectives/device/reduce_scatter.h
src/include/core.h
src/include/transport.h
src/transport.cu
src/transport/net.cu
src/transport/p2p.cu

- Performs an explicit HDP flush for GPU-based RDMA memory receives after IB verbs reports completion / local read-back finishes.
- Modifies pre-existing HDP register variable to distinguish between "next" GPU's flush register and "this" GPU's flush register (Although only 1 is ever used - next for P2P transfers, curr for IB RDMA transfers)

Adding explicit HDP flush when using RDMA via Infiniband

---

src/init.cu

Jithun reported that Ring dump is being cut short. Increase max to 64 to help multi-node optimization.

Increase debug print of ring topology to 64 ranks

---

CMakeLists.txt
src/misc/enqueue.cu
src/transport.cu

Two minor issues are solved:
+ Enclose the kernel function with parenthesis as hip-clang defines
`hipLaunchKernelGGL` as macro.
+ Need to explicitly include <hsa.h> for hip-clang.

Fix build with hip-clang

---

CMakeLists.txt
src/transport.cu

- This fix the build failures under certain environments.

Revise the previous fix to use the canonical path to HSA.

---

src/collectives/device/all_reduce.h

Summary:
1. remove the noinline attribute for AllReduceThreeKernel;
2. define COLL_UNROLL as 1 to reduce the AUTOUNROLL to either 1 or 2;
Combining 1 and 2 will reduce the scratch usage from 1256 to 952.

Tuning the inline and unroll to reduce the scratch usage

---

src/init.cc
src/transport/p2p.cc

This fixes a TensorFlow unit test where the HSA_FORCE_FINE_GRAIN_PCIE env var is not set, HIP_VISIBLE_DEVICES=0 is set, and two ranks are created on the same device.  The p2p transport should always be skipped if fine grain memory is not requested.

check for fine grain support at top of p2pCanConnect

---

tools/TransferBench/TransferBench.cpp

Adding environment variable to change timing method to match rccl-prim-test
When USE_SINGLE_SYNC is defined, only a single synchronization is done after all iterations are run, however also disables hipEvent based GPU timing

Single Sync Timing mode

---

src/transport/p2p.cc

It should be safe to increase default P2P level. We've checked fine grain VRAM and hipDeviceCanAccessPeer before sysfs path.

Change default P2P level

---

CMakeLists.txt

ROCm 3.0 is changing the naming for hip_hcc pacakge to conform to debian standards. By changing the dependency to rocm-dev, a metapackage, packaging issues can be avoided.

Changing package dependency to rocm-dev

---

src/transport/net.cc

Adding back the check which was lost from 2.5 merge.

Check fine grained memory before enabling RDMA

---

CMakeLists.txt

I tested this with hcc and it works.

set hip::host and hip::device and remove some deprecated targets

---

src/graph/xml.cc
tools/TransferBench/TransferBench.cpp

HIP-Clang does not include these HSA headers, and they need to be explicitly added in RCCL.

Fix HIP-Clang build with HSA headers

---

CMakeLists.txt

This reverts commit cd7ab1425bd5d89ff4a685c85a3dba3604e6f759.

Revert "Temporary disable 0x803 target due to build error"

---

README.md
docs/source/api.rst
src/nccl.h.in

Updated the README to include multinode support, tree algorithms, and hip-clang.
Restored the doxygen-compatible comments in nccl.h.in.  readthedocs.io should show everything again.

Updating RCCL documentation

---

src/init.cc

Also change string to RCCL, instead of NCCL. Now it says something like this: RCCL version 2.6.4+hip3.5

Report HIP version in logs

---

install.sh

Hot fix for release branch. This needs to be merged back to develop once rocm 3.5 is live.

Defaulting to hipcc in install.sh script

---

README.md
install.sh

For now, I've provided users the option to build with hcc if they still wish by replacing the --hip-clang option with --hcc.

Making hip-clang the default compiler; documentation update

---

src/collectives/device/all_reduce.h
src/collectives/device/primitives.h
src/collectives/device/prims_ll.h

This reverts commit 486fd436af929774506153095f5b272a2bb8eea7.
This workaround is no longer needed with hip-clang. Thus reverting it to make code cleaner.

Revert "Split primitive class to smaller structures"

---

install.sh
test/CMakeLists.txt
test/CorrectnessTest.hpp

No longer installing UnitTests
Removing unused HSA_FORCE_FINE_GRAIN_PCIE env variable checks

Removing UnitTest as install, removing unused env var

---

install.sh
test/CorrectnessTest.hpp
test/test_AllGather.cpp
test/test_AllReduce.cpp
test/test_AllReduceAbort.cpp
test/test_AllToAll.cpp
test/test_Broadcast.cpp
test/test_BroadcastAbort.cpp
test/test_CombinedCalls.cpp
test/test_Gather.cpp
test/test_GroupCalls.cpp
test/test_Reduce.cpp
test/test_ReduceScatter.cpp
test/test_Scatter.cpp

Unit test names are now of the format:
`[CollectiveCall]CorrectnessSweep/[CollectiveCall]CorrectnessTest.[Type of test]/[ncclRedOp_t]_[datatype]_[number of elements]_[number of devices]_[in place/out of place]_[environment variables]`
e.g. AllGatherCorrectnessSweep/AllGatherCorrectnessTest.Correctness/sum_bfloat16_3026520elements_8devices_outofplace_
This allows us to filter which unit tests we can run by the parameter values by passing the --gtest_filter command line flag, for example `--gtest_filter="AllReduceCorrectnessSweep*float32*"` will run only AllReduce correctness tests with float32 datatype.  See "Running a Subset of the Tests" at https://chromium.googlesource.com/external/github.com/google/googletest/+/HEAD/googletest/docs/advanced.md for more information on how to form more …

Adding better naming to unit tests for filtering; adding short and full unit test suites

---

tools/topo_expl/topo_expl.cpp

I found an inconsistency in the model ids and descriptions (there were 21 valid model ids but only 20 descriptions). 
This patch simplifies adding new definitions and makes it more robust.

simplify model definitions in topo expl

---

.jenkins/common.groovy
.jenkins/precheckin.groovy
.jenkins/staticlibrary.groovy
CMakeLists.txt
README.md
install.sh

Users can now choose to build RCCL as a static library by passing in -s or --static to the install script.

Adding static library building option.

---

tools/TransferBench/TransferBench.cpp
tools/TransferBench/TransferBench.hpp

- Adding missing <vector> include
- Removing unnecessary HSA_FORCE_FINE_GRAIN_PCIE requirement
- Workaround for when src == dst

Fixes to make TransferBench compile for hipclang

---

tools/TransferBench/TransferBench.cpp
tools/TransferBench/TransferBench.hpp

- Switching to hipExtLaunchKernelGGL to get more accurate GPU timings.  Major difference at small transfer sizes.
- Separate columns for total GPU bandwidth / CPU-wall time measured bandwidth
- Simplifying duration to only maximum time on GPU event / CPU wall time
- Adding column for % time spent in launch overhead
- Adding topology detection, when TransferBench is run with no arguments
- Adding 2nd method of specifying link topology (assuming identical number of thread blocks per src/dst pair)
- Modifying the code to be able to run over a number of Ns, instead of just 1 per execution

Upgrading various TransferBench features

---

CMakeLists.txt
test/CMakeLists.txt

RCCL uses -fgpu-rdc to compile its source objects. When linking
the RCCL static library, the link and archive step must do through
hipcc and uses the flag --emit-static-lib. When compiling
UnitTests, the librccl.a must be consumed through -l and -L.

Add RCCL Static Lib Creation with -fgpu-rdc

---

CMakeLists.txt

Disabling XNACK by default.  To get unit tests to pass, I had to set different flags for different gpu targets:
GFX906: sram-ecc ON
GFX908: sram-ecc OFF

Adding XNACK flags.

---

src/collectives/device/common_kernel.h
test/CMakeLists.txt
test/test_AllToAllv.cpp
test/test_AllToAllv.hpp

From https://developer.amd.com/wp-content/resources/Vega_Shader_ISA.pdf
8.1.7. Alignment
For Dword or larger reads or writes, the two LSBs of the byte-address
are ignored, thus forcing Dword alignment.

Make data alignment requirements matching ISA manual

---

CMakeLists.txt
README.md
cmake/Dependencies.cmake
install.sh

A googletest dependency check in find_package(GTest 1.10) will always pass if there is gtest already installed in the typical system directories (ie. /usr/local/lib etc.) regardless of whether or not it is 1.10 installed, which is required for our unit tests.  This is because gtest does not supply the proper cmake package config files to indicate the version.
I've re-enabled the -d/--dependency option in the install script which will force install googletest 1.10 into the build folder.   This should be used concurrently with -t to ensure the unit test build correctly picks up the gtest library dependency.   Also, I added a check to determine where the gtest library is installed, as I encountered an issue in our centos docker image where it was installed in build/release/gtest/lib64/ (vs. …

Adding the ability to force install dependencies (namely gtest); gtest library installation fix for centos

---

src/graph/paths.cc
src/graph/search.cc
src/graph/topo.h

Modifies the existing topology search code to better model how XGMI links work
Notable changes:
- XGMI speed workaround removed
- Previous XGMI count tie-break heuristic removed
- Multi-hop XGMI paths now detected, and preserved even if faster PCIe pathways present
- Sorting algorithm prefers XGMI linked GPUs over other candidate GPUs during search
- No longer short-cuts early if forced-order PCIe solution found
- Skips forced-order PCIe search for intra-node jobs
```
Differences from XGMI=24 workaround:
In some of the previous workaround, some 2-hop XGMI links were utilized. 
With these changes, 2-hop XGMI links are never selected.
Most of the differences are either clearly better, or at least on par.
====================================
Model 13 - single node 8 VEGA20 Rome
- OLD: …
```

Changes to topology based on XGMI

---

src/collectives/device/prims_ll.h

In Navi21 the buffer_wbinvl1_vol is not supported.  This workaround should achieve the same result as before but without the buffer_wbinvl1_vol instruction.  All unit tests pass with the change.

Updating inline asm to not require explicit buffer_wbinvl1_vol instruction

---

CMakeLists.txt

SWDEV-248167
Remaining errors are from rocm-cmake:
unstripped-binary-or-object, binary-or-shlib-defines-rpath, control-file-has-bad-permissions, dir-or-file-in-opt, script-without-interpreter

Fix lintian errors

---

tools/TransferBench/Makefile
tools/TransferBench/TransferBench.cpp
tools/TransferBench/TransferBench.hpp

- Adding OUTPUT_TO_CSV environment variable to generate CSV output
- Changing default number of bytes launched per link to 64MB
- Adding aggregate output information (total bandwidth / total CPU time)
- Display link info (for GPU mem cases) per line instead of at end
- Removed OpenMP
- Adding ability to generate a sample config file by specifying a negative value of N, with variety of tests.

[TransferBench] Adding output to CSV, additional changes

---

src/clique/CliqueManager.cc
src/clique/HandleCache.h

Adding explicit hipIpcCloseMemHandle to the receive cache upon cache eviction, and adding a close() call to close all memory mapped with handles in the cache.

Fixing IPC handle memory leak for CliqueKernels

---

install.sh
test/CMakeLists.txt
test/CorrectnessTest.hpp
test/test_AllGatherMultiProcess.cpp
test/test_AllGatherMultiProcess.hpp
test/test_AllReduceMultiProcess.cpp
test/test_AllReduceMultiProcess.hpp
test/test_AllToAllMultiProcess.cpp
test/test_AllToAllMultiProcess.hpp
test/test_BroadcastMultiProcess.cpp
test/test_BroadcastMultiProcess.hpp
test/test_CombinedCallsMultiProcess.cpp
test/test_CombinedCallsMultiProcess.hpp
test/test_GatherMultiProcess.cpp
test/test_GatherMultiProcess.hpp
test/test_GroupCallsMultiProcess.cpp
test/test_GroupCallsMultiProcess.hpp
test/test_ReduceMultiProcess.cpp
test/test_ReduceMultiProcess.hpp
test/test_ReduceScatterMultiProcess.cpp
test/test_ReduceScatterMultiProcess.hpp
test/test_ScatterMultiProcess.cpp
test/test_ScatterMultiProcess.hpp

The general flow of the multiprocess unit tests are as follows:
1. Launch test case as normal on root process (just like single process tests)
2. Root process initializes dataset using posix shared memory, so that all host processes can see host data as necessary
3. Root process forks child processes as necessary (1 per GPU for standard collective tests, CombinedCalls and GroupCalls have multiple GPUs per process)
4. Each child then independently runs unit test code (initializing its own 'chunk' of the dataset based on its rank, generate expected results, run collective, etc.)  Most of the unit test code logic is the same as the single process versions, just with new logic and a host-side barrier implemented with posix shared memory, to split up the work across multiple host ranks as …

Adding multiprocess unit tests

---

src/clique/CliqueManager.cc

temp files no longer created when clique mode is off.  
clique temp files are properly deleted now.

Fix temp file creation/deletion with clique mode

---

cmake/Dependencies.cmake

Prevents a double inclusion error in CMake when force installing GTest with the -d flag in the install script.  We don't need to search for an existing install of GTest in /usr/lib if we're force installing it into our build folder anyway.  This error is being seen in some combination of newer CMake versions and/or newer ROCm builds.

Do not search for existing GTest install if we're force installing it into build directory

---

src/clique/CliqueManager.cc
src/clique/CliqueManager.h
src/clique/MsgQueue.cc
src/clique/ShmObject.h

Message queues previously weren't being closed properly for CliqueManager upon clean up.  This can lead to rare problems when a subsequent RCCL run tries to initialize a message queue with the same suffix from a previous run.

Fixing message queue leak

---

src/init.cc

- Topology detection was being done after the CliqueManager topology check.  This moves things so that topology is compute first.

Fixing clique-topology detection

---

src/init.cc

"NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=INIT,COLL" enables collectives API
trace. Adding "RCCL_KERNEL_COLL_TRACE_ENABLE=1" enables kernel traces.

Use better name for kernel collective trace enable

---

src/transport/net_ib.cc

To skip Infiniband, set RCCL_IB_HCA_SKIP_LINK_LAYER=1.
To skip Ethernet, RCCL_IB_HCA_SKIP_LINK_LAYER=2.

Allow user to skip link layer with RCCL_IB_HCA_SKIP_LINK_LAYER

---

test/CorrectnessTest.hpp

Unit tests can now optionally be run with the Dataset input and output buffers allocated with hipMallocManaged().  To do so, one must opt-in by setting RCCL_USE_HMM=1 and managed/unified memory must be supported by the GPU/ROCm runtime.  Clique kernels are currently not compatible with managed memory, so we skip those tests accordingly.

Adding support for hipMallocManaged() in unit tests

---

install.sh

./install -r should just rerun the tests if already built.  Previously it would trigger a rebuild even if already built.

Fixing install script so that invoking -r alone does not trigger rebuild

---

CHANGELOG.md

Forgot to update the changelog.  The install script fix needs to be cherry-picked into 4.3 which is why I put the entry in the 4.3 release note section.

Updating changelog to show install script fix

---

test/CorrectnessTest.hpp
test/test_AllGather.cpp
test/test_AllReduce.cpp
test/test_AllReduceAbort.cpp
test/test_AllReduceGroup.cpp
test/test_Broadcast.cpp
test/test_BroadcastAbort.cpp
test/test_CombinedCalls.cpp
test/test_GroupCalls.cpp
test/test_Reduce.cpp
test/test_ReduceScatter.cpp

This is due to a bug with the ExtractSubDataset() function not fully initializing subDataset, specifically the function member.  We were getting lucky with the default uninitialized value in non-release mode.  In release mode, the uninitialized value was wrong enough to throw off the Dataset NumBytes() function causing the actual failure.  I don't know why in release mode the default value is different though.  Shouldn't all enum default values be 0?  Oh well.
I also explicitly set the Dataset function for certain unit tests that weren't doing it already.

Fixing unit test failure when googletest is built in release mode

---

tools/TransferBench/EnvVars.hpp
tools/TransferBench/TransferBench.cpp
tools/TransferBench/TransferBench.hpp

Allows users to specify source data pattern for copies using FILL_PATTERN environment variable (specified in hex).
The pattern gets repeated across the length of the data.

[TransferBench] Adding ability to specify source data pattern

---

src/init.cc
src/transport/coll_net.cc
src/transport/net.cc
src/transport/p2p.cc
src/transport/shm.cc

Added the information of "comm",  "nRanks", and "busId" to multiple INFO(NCCL_INIT) lines and the COLLTRACE mode. It enables us to identify device groups and solve the issues of the topology visualizer and the collective trace processor when a device has more than one communicator/nRanks.

Enhancement of RCCL logging information for topology-aware optimization

---

CMakeLists.txt
cmake/Dependencies.cmake

Use `rocm_install` in place of `install` to install to the development package.
Update rocm-cmake to the required version. In order for CMake to detect the version, rocm-cmake must be build and installed, here to a local directory.

Setup runtime and development packages

---

tools/TransferBench/TransferBench.cpp
tools/TransferBench/TransferBench.hpp

- Removing dependency on hip_fp16 header file, which may be renamed in some versions of ROCm.
- Fixing swapped executor / source header in CSV output

[TransferBench] Removing dependency on hip_fp16 header, CSV header fix

---

tools/TransferBench/TransferBench.cpp

- Adds ability to specify a suffix of 'K', 'M', or 'G' to specify (kilobytes / megabytes / gigabytes) for numBytes argument.

[TransferBench] Adding ability to specify suffix for numBytes

---

tools/TransferBench/EnvVars.hpp
tools/TransferBench/TransferBench.cpp
tools/TransferBench/TransferBench.hpp

- Adding a p2p benchmark mode to TransferBench (activated via specifying "p2p") as configFile
- Setting USE_SINGLE_SYNC=1 by default

TransferBench p2p benchmark mode

---

test/CMakeLists.txt

Now do a regex search for /opt/rocm*

Fixing cmake_install_prefix search to include /opt/rocm-xxxx

---

tools/TransferBench/TransferBench.cpp
tools/TransferBench/TransferBench.hpp

- Adding argument to p2p benchmark mode to specify number of CUs to use (default is still max available on device)
- Adding tables for remote read / local write transfers

[TransferBench] Adding #CUs / RRLW mode to p2p benchmark

---

test/CMakeLists.txt

The previous fix had issues on centos.  Using ${ROCM_PATH} which is automatically detected by cmake should be bulletproof as it should always point to the correct directory.

Remove hardcoded references to /opt/rocm when using chrpath

---

install.sh
test/CMakeLists.txt

In the centos docker images I've encountered, the ROCM_PATH environment variable is set.  In Ubuntu it is not.  This can lead to a mismatch of CMAKE_INSTALL_PREFIX in CMake (https://github.com/ROCmSoftwarePlatform/rccl/blob/develop/CMakeLists.txt#L24), as in the install script we pass in -DCMAKE_INSTALL_PREFIX=ROCM_PATH, where ROCM_PATH is set to /opt/rocm (which can be a symlink), whereas in the CMake code we set ROCM_PATH to /opt/rocm **after** resolving the symlink.
I now set ROCM_PATH in the install script to remove any ambiguity.  This was leading to unit test build failures with my recent chrpath changes.

Set ROCM_PATH CMake variable in install script

---

test/CMakeLists.txt

Small syntax error meant gtest_num_gpus wasn't getting set to 2 at all, leading to weird GTest error messages instead of skipping tests.

Fixing setting of GPUs to 2 when 1 or less GPUs on system for unit tests

---

tools/TransferBench/EnvVars.hpp
tools/TransferBench/Kernels.hpp
tools/TransferBench/Makefile
tools/TransferBench/TransferBench.cpp
tools/TransferBench/TransferBench.hpp

- Updating TransferBench to work with 2.11.4 by decoupling copy kernel and using custom copy kernel

[TransferBench] Updating for 2.11.4.  Decoupling from RCCL kernel

---

cmake/Dependencies.cmake

Set GTEST_BOTH_LIBRARIES before searching for GTest package after installing locally.  Otherwise it might look in /usr/local/lib instead.

Search for GTest 1.11; fix detection of GTest after install

---

tools/TransferBench/EnvVars.hpp
tools/TransferBench/TransferBench.cpp
tools/TransferBench/TransferBench.hpp

Adding new GPU indexing mode based on PCIe bus address, instead of ROCr/HIP device numbers

TransferBench: Adding ability to reindex GPUs based on PCIe address

---

src/clique/AllReduceCliqueKernel.h
src/clique/CliqueCommon.h
src/clique/CliqueCommonKernel.h
src/clique/CliqueManager.cc
src/collectives/device/all_reduce.h

It allows us to compile host code files and kernel code files separately by using different compiler and flags

[rocm-4.4] separate kernel code into separate header

---

test/AllReduce_GroupCall.cpp
test/AllReduce_PreMultScalar.cpp
test/SendRecv_SinglePairs.cpp
test/common/TestBed.cpp
test/common/TestBedChild.cpp
test/common/TestBedChild.hpp

- Switching from NCCL_COMM_ID to passing ncclUniqueId from first rank to all other ranks via parent process.
- Minor test name renaming for consistency

Changing initialization method for UnitTests

---

cmake/Dependencies.cmake
tools/HelloRccl/Makefile
tools/TransferBench/Makefile
tools/ib-test/Makefile
tools/rccl-prim-test/Makefile
tools/topo_expl/Makefile

We install the ROCM package under home directory so that multiple staffs can share the same machine with different ROCM version.  However, several places in RCCL hardcode /opt/rocm. This patch tries to fix it.

Replace hardcoded /opt/rocm with ROCM_PATH env var

---

CMakeLists.txt

librrcl.so is is having a dead soft link. Which is causing issues with tensor flow build. Fixing it.

Fixing the broken library soft link

---

tools/TransferBench/CHANGELOG.md
tools/TransferBench/EnvVars.hpp
tools/TransferBench/TransferBench.cpp
tools/TransferBench/TransferBench.hpp
tools/TransferBench/example.cfg

- Setting NUM_ITERATIONS to negative number indicates to run for -NUM_ITERATIONS seconds per Test
- Copies are now refered to as Transfers instead of Links
- Re-ordering how env vars are displayed (alphabetically now)
- Combined timing is now always on for kernel-based GPU copies. COMBINED_TIMING env var has been removed
- Use single sync is no longer supported to facility variable iterations. USE_SINGLE_SYNC env var has been removed

[TransferBench] Syncing with TransferBench v1.02

---

CMakeLists.txt
cmake/git_version.cmake
src/include/git_version.h
src/init.cc

Adding git information (if available) to RCCL info line display.
A plus sign is added to hash to denote local changes
Version file is updated during build (does not require CMake reconfigure)
e.g: RCCL version 2.12.12+hip5.2 develop:b630976+

Adding git hash info to version output line

---

src/clique/AllReduceCliqueKernel.h
src/clique/CliqueCommon.h
src/clique/CliqueCommonKernel.h
src/clique/CliqueManager.cc
src/collectives/device/common.h

This PR contains two fixes when adapting to buck based compiling system:
1. Fix misleading indentation compiling error 
2. Separate clique kernel code into separate header
Please note commit 2 is not necessary for the current develop branch since clique code have been disabled. However, we have seem such an issue when adapting previous releases (e.g., rocm-5.1.0, 5.1.3) and assume the clique code may be re-enabled in future. Thus, we want to upstream this change.
If it is feasible, can we also merge these two PRs into the main develop branch to ensure future releases will include them?

Fixes issues when adapting to buck compilation

---

CHANGELOG.md
CMakeLists.txt

Reverts ROCmSoftwarePlatform/rccl#570

Revert "Adding the missing roc:: namespace"

---

CHANGELOG.md
src/include/socket.h
src/misc/socket.cc
src/transport/net_ib.cc

Reduce AlltoAll port usage by reusing socket ports when connect/accept in send/recv proxy.
Existing issue
--------------
Running AlltoAll on >=64 MI200 nodes (16 GPUs per node) will suffer `Call to bind failed : Address already in use` error, because it requires >32k free ports but by default Linux only has ~28k ephemeral ports.
Root cause
----------
In AlltoAll, each rank needs to establish `p2pnChannelsPerPeer` channels with any other ranks. Cross node NET/IB channels will use TCP sockets to initialize IB connection, for these channels:
* in send proxy, current rank needs to connect (`ncclNetConnect`) to remote rank in `sendProxyConnect`, a new port will be allocated by `connect` system call in net plugin
* in recv proxy, current rank needs to accept (`ncclNetAccept`) from remote rank …

Reduce AlltoAll port usage in send/recv proxy

---

src/transport/coll_net.cc
src/transport/net.cc
src/transport/p2p.cc
src/transport/shm.cc

Added the information of "comm", "nRanks", and "busId" to multiple INFO(NCCL_INIT) lines and the COLLTRACE mode. It enables us to identify device groups and solve the issues of the topology visualizer and the collective trace processor when a device has more than one communicator/nRanks.

Enhancement of RCCL logging information for topology-aware utilities

---

tools/HelloRccl/Makefile
tools/MultiRank/Makefile
tools/ib-test/Makefile
tools/rccl-prim-test/Makefile
tools/topo_expl/Makefile

Proposed Changes:
- Updated default path for hip to ROCM_PATH (/opt/rocm instead of /opt/rocm/hip) as per new/current structure.

HIP Path default updated to ROCM_PATH (reorg path)

---

src/include/BfdBacktrace.hpp

include stdlib.h to fix compilation error in rccl :
[39/58] Building CXX object CMakeFiles/rccl.dir/src/misc/signals.cc.o
FAILED: CMakeFiles/rccl.dir/src/misc/signals.cc.o 
/opt/rocm/bin/hipcc -DENABLE_COLLTRACE -DHAVE_BFD -DHAVE_CPLUS_DEMANGLE -DUSE_ROCM_SMI64CONFIG -D__HIP_PLATFORM_AMD__=1 -D__HIP_PLATFORM_HCC__=1 -Drccl_EXPORTS -I/home/cosmo/build/flgrwqa/build/include -I/home/cosmo/build/flgrwqa/build/include/rccl -I/home/cosmo/build/flgrwqa/rccl/src -I/home/cosmo/build/flgrwqa/rccl/src/include -I/home/cosmo/build/flgrwqa/rccl/src/collectives -I/home/cosmo/build/flgrwqa/rccl/src/collectives/device -I/opt/hsa/include -fPIC -fvisibility=hidden -fgpu-rdc -parallel-jobs=8 -Wno-format-nonliteral -x hip --offload-arch=gfx803 --offload-arch=gfx900:xnack- --offload-arch=gfx906:xnack- …

fix error: use of undeclared identifier 'free'

---

src/init.cc

fix channel count for multi-rank scenarios.
No further modification required for the current tree algorithm.

Expand ncclTreeBasePostset for multi-rank

---

src/collectives/device/common.h
src/transport/net.cc
src/transport/p2p.cc

These issues are found when compiling with buck but the fixes are generic to all compilers.

Fix compilation issues with buck

---

src/collectives/device/all_reduce.h
src/collectives/device/common.h
src/collectives/device/op128.h
src/collectives/device/prims_ll128.h
src/enqueue.cc
src/graph/rome_models.cc
src/graph/topo.h
src/graph/tuning.cc
src/include/collectives.h
src/include/comm.h
src/include/devcomm.h
src/include/enqueue.h
src/init.cc

Only enabled for gfx90a when configured with LL128=1:
CXX=/opt/rocm/bin/hipcc cmake -DCMAKE_PREFIX_PATH=/opt/rocm/ -DLL128=1 ..

Enable LL128 protocol support

---

src/misc/strongstream.cc
src/transport.cc

This reverts commit 36e453c61e8ddc5913ffc411f9e9bd2cc7090d6a.
Add stream synchronization in ncclStrongStreamRelease.

Revert "Ensure memory copy integrity during transport setup (#731)"

---

src/misc/msccl/msccl_setup.cc

Added a RCCL_MSCCL_ENABLE_DONE_EVENT env var, set it be 1 by default.
The env var is to control whether to use doneEvent when invoking MSCCL kernels.
Skipping doneEvent would cause the firmware to skip L2 cache flush, resulting in overall performance improvement.

Allow skipping doneEvent inside MSCCL.

---

src/collectives/device/common.h

The default value of the unroll factor is 2. Changing the unroll factor to 4 provides better performance for most of the collectives.

device: change unroll factor

---

src/collectives/device/prims_ll128.h
src/include/devcomm.h

Instead of directly wrapping a platform-specific operation with a preprocessor check against a gfx macro, it can be more flexible to check a macro that can be overriden by the user. The gfx macro can then just provide the default value for the macro, resulting in the same default behaviour as if the gfx macro was checked directly but with more control at build-time.
For example, to build rccl without using buffer_wbinvl1_vol on gfx902, but still use the default on other archs, a user could `export CXXFLAGS='-Xarch_gfx902 -DRCCL_USE_WBINVL1_VOL=0'` before configuring the build. This flexibility isn't always necessary, but it's nicer to have it and not need it than to need it and not have it.
(This patch was originally written for ROCm 5.3.3 to enable gfx1010 and gfx1011 to build. The diff …

Fix build on additional architectures

---

.jenkins/extended.groovy
.jenkins/precheckin.groovy
.jenkins/staticlibrary.groovy
install.sh
src/collectives/device/common.h
src/enqueue.cc
src/graph/topo.h
tools/time-trace/rccl-TimeTrace.sh
tools/time-trace/time_trace_generator.py

* Disabled generating additional debug kernels when using the fast option in install.sh.
* Removed the --max-jobs flag and added the --limit-nprocs flag. The default value is now set to the maximum number of processors. The limiting functionality is intended for use in the CI environment.
* Modified time_trace_generator.py and rccl-TimeTrace.sh to avoid specifying static paths to folder and file locations.
* Modified topo.h, common.h, and enqueue.cc to resolve compiler errors when colltrace is disabled.

Disable Colltrace for --fast option

---

.jenkins/extended.groovy
.jenkins/precheckin.groovy
.jenkins/staticlibrary.groovy
README.md
install.sh

- Adding new install.sh option (-j / --jobs) to specify how many parallel jobs to use (16 by default)
- Added short form option -f for --fast
- Added short form option -l for --local_gpu_only
- Updating install.sh README section
- Removing limit_nprocs option from install.sh, and associated CI files

Limiting # parallel jobs in install script to 16 by default

---

test/common/EnvVars.cpp
test/common/EnvVars.hpp
test/common/main.cpp

- Print off values of unit test environment variables as part of unit tests:
```
Example Output:
================================================================================
Environment variables:
- UT_SHOW_NAMES        Show test case names                       (  1) <unset>
- UT_MIN_GPUS          Minimum number of GPUs to use              (  2) <unset>
- UT_MAX_GPUS          Maximum number of GPUs to use              ( 16) <unset>
- UT_POW2_GPUS         Only allow power-of-2 # of GPUs            (  0) <unset>
- UT_PROCESS_MASK      Whether to run single/multi process        (  3) <unset>
- UT_VERBOSE           Show verbose unit test output              (  0) <unset>
- UT_REDOPS            List of reduction ops to test              ( -1) <unset>
- UT_DATATYPES         List of …
```

Report unit test environment variable values as part of output

---

src/collectives/device/common.h
src/collectives/device/common_kernel.h

With Simple protocol, unroll factor of 4 offers better performance for most of the collectives (on MI200. MI250, and MI300) except large message allreduce with Ring algorithm on MI250 and MI200). This PR changes the default unroll factor to 4 while adding fine tuning for reduction operations.

device: fine tune MI200/MI250 simple protocol performance

---

test/CMakeLists.txt

- There was a previous workaround for unit tests involving chrpath which can now be removed.

Removing unnecessary chrpath check for unit tests

---

src/include/msccl/msccl_struct.h

This is no longer valid. They can only be simple escape sequences. Removing '\' fixes issue. Assert message now compiles and emits the '%' as expected.

Fix static_assert string literal that contains a "\%".

---

src/collectives/device/common.h
src/collectives/device/sendrecv.h

This commit optimizes the unrolling factor for collectives for MI100 machines.
The default value for COLL_UNROLL is 2 which delivers better performance for most of the collective operations.
For sendrecv, gather, and scatter collectives COLL_UNROLL 4 is used because delivers better performance compared to COLL_UNROLL=2.
Link to the corresponding Jira tasks:
https://ontrack-internal.amd.com/browse/SWDEV-412970:
[ROCm QA][IV][QR][G][MI100]~6% Performance drop in RCCL " broadcast_perf-bench"
https://ontrack-internal.amd.com/browse/LWPCOMMLIBS-76:
Experiment with RCCL Simple Protocol on MI100

optimizing COLL_UNROLL for MI100 machines

---

src/collectives/device/primitives.h
src/collectives/device/prims_ll.h
src/collectives/device/prims_simple.h
src/enqueue.cc
src/graph/tuning.cc

* gfx11: don't use LL for sendrecv
* Use builtin instead of inline asm
(cherry picked from commit f70e3e569bb2d8b9e43e75aabfe528d6feeb2485)

gfx11: don't use LL for sendrecv (#853)

---

CMakeLists.txt
install.sh

revert the logic to ensure that we are not accidentally creating a dependency on the bfd libraries when deploying rccl binaries.

turn bfd compilation off by default

---

src/graph/paths.cc

This reverts commit 16dd05a58a948eeb3de9c484dbe5e5ffb4e7295e.
This revert resolves the ~19% performance drop with gather and ~40% with sendrecv tests.
The hang for alltoallv is not observed with develop branch for both 4 and 8 gpus.
Performance drop observed for alltoallv with this revert, but there is a workaround for now (NCCL_MAX_P2P_NCHANNELS=2).

Revert "Remove 2H4P condition from P2P channels adjustment (#890)"

---

CMakeLists.txt

The quotes around "-fsanitize=address -shared-libasan" cause the BUILD_ADDRESS_SANITIZER build to fail; remove the quotes

Remove quotes causing asan build breakage

---

tools/msccl-algorithms/allgather-allpairs-16n-16tb.xml

Empirical testing suggests allgather needs to be tuned for MSCCL.
Benchmarking command:
```
mpirun.mpich -np 16 -env LD_LIBRARY_PATH=/opt/rocm/hip/lib:~/projects/rccl/build ./build/all_gather_perf -b 64 -e 1M -f 2 -g 1 -n 250
```
Before:
```
64             1     float    33.75    0.00    0.00  0e+00    33.61    0.00    0.00  0e+00
128             2     float    33.65    0.00    0.00  0e+00    33.78    0.00    0.00  0e+00
256             4     float    33.72    0.01    0.01  0e+00    33.83    0.01    0.01  0e+00
512             8     float    33.97    0.02    0.01  0e+00    33.72    0.02    0.01  0e+00
1024            16     float    33.89    0.03    0.03  0e+00    33.93    0.03    0.03  0e+00
2048            32     float    34.12    0.06    0.06  0e+00    34.09    0.06    0.06  0e+00
4096 …
```

Introduce allgather MSCCL XML specification for MI250X up to 320KB.

---

src/collectives/device/msccl_kernel_impl.h

On AMD GCN ISA, the semantic of nontemporal store already guarantee data fully visible on remote GPU. There shouldn't be no barriers needed after send, under all-to-all communication pattern.
Empirical performance benchmarking shows improvement in smaller message sizes with correct results.

Do not add barrier after send
